### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by mush60** [mush60/xcrud#2]

**Comment by shahkv95** [comment]
@mush60 can you pls tell me what is the issue that you have raised?

**Comment by mush60** [comment]
> @mush60 can you pls tell me what is the issue that you have raised?

hay shakv95, the issue is to add a crud app using certain frameworks and certain languages ​​to this repository so that it can be used by others to learn new frameworks

**Comment by Aveesh52** [comment]
Hey can I contribute to this project?

**Comment by mush60** [comment]
of course brother
